development: &default
  adapter: postgresql
  encoding: unicode
  database: coffin_rails_development
  pool: 5

test:
  <<: *default
  database: coffin_rails_test

production:
  <<: *default
  database: coffin_rails_production